import os
from pydoc import text
from openai import OpenAI
from dotenv import load_dotenv
load_dotenv()
import requests
OPEN_API_KEY = os.getenv("OPENAI_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
OEPNROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
print("✅ API Keys successfully loaded from .env file")
print(OPEN_API_KEY[:10] if OPEN_API_KEY else "Missing OPENAI key")  
print(TAVILY_API_KEY[:10] if TAVILY_API_KEY else "Missing TAVILY key")
print(OEPNROUTER_API_KEY[:10] if OEPNROUTER_API_KEY else "Missing OEPNROUTER API KEY key")
Openai_client=OpenAI(api_key=OPEN_API_KEY)
print("OpenAI Client is successfully configured")
from typing_extensions import TypedDict
from agents import function_tool   # Importing multiple tools for agent functionality


class TavilySearchParams(TypedDict):
    query: str
    max_results: int
@function_tool()
def tavily_search(params: TavilySearchParams) -> str:
    """calls the Tavily API and returns the string summarry of search results.
    params: TavilySearchParams : a dictionary with keys 'query' (the search query) and 'max_results' (the maximum number of results to return)
    returns: a string summarizing the search results from the Tavily API
    """
    url = "https://api.tavily.com/search"
    headers = {
        #"Authorization": f"Bearer {TAVILY_API_KEY}",
        "Content-Type": "application/json"
    }
    payload = {
        "api_key": TAVILY_API_KEY,
        "query": params["query"],
        "max_results": params.get("max_results", 3)
    }
    response = requests.post(url, json=payload, headers=headers)
    if response.status_code == 200:
        results= response.json().get("results",[]) # Extracting the 'results' field from the API response, defaulting to an empty list if not present
        summary = "\n".join(
            [f"{i+1}. {result['title']} - {result['content']}"
              for i, result in enumerate(results)]) # Creating a summary string by enumerating through the search results and formatting each result with its title and content 
        return summary if summary else "No results found."
    else:
        raise Exception(f"Tavily API error: {response.status_code} - {response.text}")
from agents import Agent , Runner , SQLiteSession

class AnalysisSummary(TypedDict):
    summary: str
    
#creating an AI agent called  research_agent with access to  the tavily_search. The agent is designed to perform market research by utilizing the tavily_search tool to gather information and the code_interpreter tool to analyze data and generate insights based on the search results. The agent's instructions guide it to use these tools effectively to provide comprehensive market research summaries.
Research_agent=Agent(
    name="Research Agent",
    instructions="""## Context
        You are a research agent with access to the Tavily search tool.
        
        ## Instruction
        Given a user query, use the Tavily search tool to find relevant information and summarize the key findings.
        
        ## Input
        - A research query from the user.
        
        ## Output
        - A summary of key findings in a maximum of 5 bullet points.""",
        model="gpt-4o",
        tools=[tavily_search],
        output_type=(AnalysisSummary)
)
print("✅ research agent AI agent us now ready")

# Let's define our Analyst AI Agent which will take the research notes from the Research Agent and analyze them to extract key trends, risks, or insights. The agent will be designed to provide a concise analysis in no more than 2 paragraphs based on the research notes it receives.
analyst_agent = Agent(name = "Analyst",
                      instructions = """

        ## Context
        You are an analyst who receives research notes generated by the research agent.
        
        ## Instruction
        Given the research notes, analyze the content and extract key trends, risks, or insights.
        
        ## Input
        - Research notes (summaries of findings from the research agent).
        
        ## Output
        - A concise analysis (no more than 2 paragraphs) highlighting key trends, risks, or insights.
        """,

        model = "gpt-4.1-mini",
        output_type = AnalysisSummary,
)

print("✅ Analyst AI agent us now ready")

class FinalReport(TypedDict):    # This is a Pydantic model that defines the structure of the final report generated by the Writter agent. It includes a short summary, a markdown-formatted report, and a list of follow-up questions for further research or analysis based on the findings.
    short_summary: str
    markdown_report: str
    follow_up_questions: list[str]  # List of follow-up questions for further research or analysis based on the findings.
    
Writter_agent = Agent(name = "Writter",
     instructions = """You are a senior market analyst tasked with generating an executive-level research report.
         ## Context
         You will receive:
         - The original user query (the research question or topic of interest).
         - Summaries and analyses generated by helper tools: 'researcher_agent' (for bullet-point research findings) and 'analyst_agent'.
         You may call these helper tools as needed to gather additional information or clarify findings.
         ## Instructions
         Your job is to synthesize all available information and produce the following outputs:
         1. **Executive Summary:** Write a concise summary (2–3 sentences) highlighting the most important findings relevant to the original query.
         2. **Detailed Markdown Report:** Compose a comprehensive, well-structured report in markdown format (at least 500 words).
         3. **Follow-up Research Questions:** Suggest 3–5 thoughtful follow-up questions for further investigation.
         ## Input
         - The original user query.
         - Summaries and analyses from the helper tools.
         ## Output
         Return a structured object with:
         - `short_summary`: The executive summary.
         - `markdown_report`: The detailed markdown report.
         - `follow_up_questions`: A list of 3–5 follow-up research questions.
         """,
    
        model="gpt-4.1-mini",
        output_type=FinalReport
     )
print("✅ Writter AI agent us now ready")

session=SQLiteSession("MultiAgentSystem.db")

import asyncio
async def manager_run(user_query :str):
    
    print(f"User Query: {user_query}")
    # Step 1: Research Agent gathers information using the tavily_search tool
    research_result = await Runner.run(Research_agent,user_query, session=session)
    research_sumary=research_result.summary
    print(f"Research Summary:\n{research_sumary}")
    
    # Step 2: Analyst Agent analyzes the research summary to extract insights
    analysis_result = await Runner.run(analyst_agent,research_sumary, session=session)
    analysis_summary =analysis_result.summary
    print(f"Analysis Summary:\n{analysis_summary }")
    
    # Step 3: Writter Agent synthesizes the research and analysis into a final report
    # final_report = await Writter_agent.run({
    #     "original_query": user_query,
    #     "research_summary": research_sumary,
    #     "analysis_result": analysis_result
    # }, session=session)
    
#     final_report = await Runner.run(
#     Writter_agent,
#     {
#         "original_query": user_query,
#         "research_summary": research_sumary,
#         "analysis_result": analysis_summary
#     },
#     session=session
# )
    writer_prompt = f"""ORIGINAL QUERY:{user_query} RESEARCH SUMMARY:{research_sumary}ANALYSIS RESULT:{analysis_summary}
    Generate the final report.
    """
    
    final_report = await Runner.run(
        Writter_agent,
        writer_prompt,
        session=session
    )
        
    return final_report

# Example usage
user_query = """This question requires up-to-date information.
Use the tavily_search tool to collect recent news, releases, and market analysis about electric gadgets in 2026.
Summarize the findings in bullet points."""

final_response = asyncio.run(manager_run(user_query))
final_report = final_response.content  # dict

print("\n=== Final Report ===")
print(f"Executive Summary:\n{final_report['short_summary']}\n")
print(f"Markdown Report:\n{final_report['markdown_report']}\n")
print("Follow-up Questions:")
for q in final_report['follow_up_questions']:
    print(f"- {q}")
